# Generated by Django 4.0.1 on 2022-01-31 14:57

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_type', models.IntegerField(choices=[(1, 'ADMIN'), (2, 'VIP-Client'), (3, 'CLIENT')], default=3, verbose_name='Тип Пользователя')),
                ('phone_number', models.CharField(max_length=100, verbose_name='phone_number')),
                ('age', models.IntegerField()),
                ('gender', models.IntegerField(choices=[(1, 'MALE'), (2, 'FEMALE'), (3, 'OTHER')], verbose_name='Гендер')),
                ('place_of_birth', models.IntegerField(choices=[(1, 'UNITED STATES AMERICA'), (2, 'CHINA PRC'), (3, 'INDIA REPUBLIC'), (4, 'FRANCE REPUBLIC'), (5, 'RUSSIAN FEDERATION'), (6, 'GERMANY FEDERAL REPUBLIC'), (7, 'JAPAN'), (8, 'KYRGYZ REPUBLIC'), (9, 'KAZAKHSTAN')], verbose_name='Место рождения')),
                ('degree_education', models.IntegerField(choices=[(1, 'PRIMARY DEGREE EDUCATION'), (2, 'INCOMPLETE SECONDARY DEGREE EDUCATION'), (3, 'FULL SECONDARY DEGREE EDUCATION'), (4, 'SECONDARY SPECIAL DEGREE EDUCATION'), (5, 'HIGHER PROFESSIONAL DEGREE EDUCATION'), (6, 'BACHELORS DEGREE EDUCATION'), (7, 'MASTERS DEGREE EDUCATION')], verbose_name='Степень образования')),
                ('final_question', models.CharField(max_length=50, verbose_name='Ваша любимая книга?')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
